AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'zoho_sign.gemspec'
    - 'spec/**/*.rb'
