name: Create gem release and publish

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version (Use format X.X.X. Example: 1.42.5)'
        required: true
        type: string
        default: '0.0.0'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    
    - name: Install gem-release (to prepare the release version)
      run: |
        gem install gem-release --version '~> 2.2'
    
    - name: Prepare the enviroment and the release
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem bump --sign --push --tag --version '${{ inputs.release_version }}' --message ':arrow_up: Prepare release v%{version} %{skip_ci}'

    - name: Publish to GPR
      run: |
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      run: |
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
